input {
  beats {
    port => 5044
  },
  file {
    path => "/usr/share/logstash/data/core-service.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "core-service-logs-%{+YYYY.MM.dd}"
  }
}