services:
#  payment-service:
#    build:
#      context: ../payment-observe
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/paymentdb
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=pass
#      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
#      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
#      - LOKI_URL=http://loki:3100/loki/api/v1/push
#      - DEPLOYMENT=docker-compose
#      - LOGGING_PATH=/Users/samreachyan/app_log/core-service.log
#    depends_on:
#      - db
#      - zipkin
#    networks:
#      - payment-network
#    volumes:
#      - ./payment_logs:/Users/samreachyan/app_log

  db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=grafana
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - payment-network

  # Observability for app
  grafana:
    image: docker.io/grafana/grafana-oss:10.4.2
    container_name: grafana
    depends_on:
      - loki
      - prometheus
      - tempo
    ports:
      - "3000:3000"
    hostname: ${HOST_NAME:-localhost}
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_DATABASE_USER=user
      - GF_DATABASE_PASSWORD=password
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - payment-network

  alloy:
    image: docker.io/grafana/alloy:v1.0.0
    container_name: alloy
    command:
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--storage.path=/data-alloy"
      - "--disable-reporting"
      - "/etc/alloy/config.alloy"
    depends_on:
      - loki
      - prometheus
      - tempo
    hostname: ${HOST_NAME:-localhost}
    environment:
      - ENVIRONMENT=dev
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - PROMETHEUS_URL=http://prometheus:9090/api/v1/write
      - TEMPO_URL=http://tempo:4317
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
      - ./alloy-data:/data-alloy
    restart: unless-stopped
    networks:
      - payment-network

  loki:
    image: docker.io/grafana/loki:2.9.7
    container_name: loki
    command: -config.file=/etc/config/loki.yml
    ports:
      - "3100:3100"
    hostname: ${HOST_NAME:-localhost}
    volumes:
      - ./loki/loki.yml:/etc/config/loki.yml
    restart: unless-stopped
    networks:
      - payment-network

  prometheus:
    image: quay.io/prometheus/prometheus:v2.51.2
    container_name: prometheus
    command:
      - "--config.file=/etc/config/prometheus.yml"
      - "--enable-feature=otlp-write-receiver"
      - "--enable-feature=exemplar-storage"
      - "--web.enable-remote-write-receiver"
    ports:
      - "9090:9090"
    hostname: ${HOST_NAME:-localhost}
    volumes:
      - ./prometheus/prometheus.yml:/etc/config/prometheus.yml
    restart: unless-stopped
    networks:
      - payment-network

  tempo:
    image: docker.io/grafana/tempo:2.4.1
    container_name: tempo
    command: -config.file /etc/tempo-config.yml
    ports:
      - "3110"     # Tempo
      - "4317"     # OTLP gRPC
      - "4318"     # OTLP HTTP
      - "9411:9411"     # zipkin
    hostname: ${HOST_NAME:-localhost}
    volumes:
      - ./tempo/tempo.yml:/etc/tempo-config.yml
    restart: unless-stopped
    networks:
      - payment-network

  ## Grafana OnCall OSS
#  oncall:
#    image: grafana/oncall:v1.15.6
#    container_name: grafana-oncall
#    environment:
#      - SECRET_KEY=super-secret-key
#      - DJANGO_SUPERUSER_USERNAME=admin
#      - DJANGO_SUPERUSER_PASSWORD=admin
#      - DJANGO_SUPERUSER_EMAIL=admin@example.com
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./oncall:/data

volumes:
  db_data:
  grafana-data:
  es_data:
  alloy-data:
  payment_logs:

networks:
  payment-network:
    driver: bridge
