x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    mode: non-blocking
    max-buffer-size: 4m
    loki-retries: "3"
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) - (?P<level>[A-Z]{4,5}) - \[(?P<trace_id>[a-z0-9]*)-(?P<span_id>[a-z0-9]*)\] - (?P<message>.*)$'
#          expression: '^(?P<date>\d{4}-\d{2}-\d{2})T(?P<time>\d{2}:\d{2}:\d{2}.\d{3}) (?P<message>(?s:.*))$$'

x-app-dependencies: &app-dependencies
  loki:
    condition: service_healthy
  db:
    condition: service_healthy

services:
  # Database
  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=grafana
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U grafana" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging: *default-logging
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - payment-network

  # Infrastructure
  loki:
    image: grafana/loki:3.7
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - payment-network
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # Prometheus Obs
  prometheus:
    image: prom/prometheus:v3.11.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki
    logging: *default-logging
    networks:
      - payment-network

  # Tempo
  tempo:
    image: grafana/tempo:2.9.2
    command: [ "-config.file=/etc/tempo.yml", "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3200:3200" # Expose Tempo's HTTP API on port 3200
      - "9095:9095" # Expose Tempo's gRPC API on port 9095 for Grafana's tracesToProfiles feature
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
      - ./tempo_data:/tmp/tempo
    depends_on:
      - loki
    logging: *default-logging
    networks:
      - payment-network

  # Observability for app
  grafana:
    image: grafana/grafana-oss:12.0.1
    ports:
      - "3000:3000"
    environment:
      - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=tempo:4317
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=db:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=user
#      - GF_DATABASE_SSL_MODE=disable
      - GF_DATABASE_PASSWORD=password
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml     # dashboard.yml only
      - ./grafana/applications:/etc/grafana/dashboards   # contains dashboards json file
#      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - loki
      - prometheus
      - tempo
    logging: *default-logging
    networks:
      - payment-network

  # Applications
  payment-service-a:
    build:
      context: ../payment-observe
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/grafana
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317 # send traces to Tempo
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc # use gRPC for OTLP
      - OTEL_SERVICE_NAME=payment-service-a # service name for Span
      - OTEL_METRICS_EXPORTER=none # disable metrics exporter
      - OTEL_LOGS_EXPORTER=none # disable logs exporter
      - MANAGEMENT_METRICS_TAGS_APPLICATION=payment-service-a # override default value of management.metrics.tags.application in app/src/main/resources/application.properties
    ports:
      - "8080:8080"
    logging: *default-logging
    depends_on: *app-dependencies
    networks:
      - payment-network

  payment-service-b:
    build:
      context: ../payment-observe
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/grafana
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317 # send traces to Tempo
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc # use gRPC for OTLP
      - OTEL_SERVICE_NAME=payment-service-b # service name for Span
      - OTEL_METRICS_EXPORTER=none # disable metrics exporter
      - OTEL_LOGS_EXPORTER=none # disable logs exporter
      - MANAGEMENT_METRICS_TAGS_APPLICATION=payment-service-b # override default value of management.metrics.tags.application in app/src/main/resources/application.properties
    ports:
      - "8081:8080"
    logging: *default-logging
    depends_on: *app-dependencies
    networks:
      - payment-network

volumes:
  db_data:
  tempo_data:
  payment_logs:

networks:
  payment-network:
    driver: bridge
