server:
  port: 8080

spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentdb}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sleuth:
    sampler:
      probability: ${SPRING_SLEUTH_SAMPLER_PROBABILITY:1.0}
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}

logging:
  file:
    name: /app/logs/core-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%traceId] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics

  metrics:
    export:
      prometheus:
        enabled: true

  tracing:
    sampling:
      probability: 1.0
