server:
  port: 8080

elasticsearch:
  url: ${ELASTIC_URL:http://localhost:9200}

spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/grafana}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10

  data:
    elasticsearch:
      cluster-nodes: ${ELASTIC_URL:http://localhost:9200}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sleuth:
    sampler:
      probability: ${SPRING_SLEUTH_SAMPLER_PROBABILITY:1.0}
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}

logging:
  file:
    name: ${LOGGING_PATH:/Users/samreachyan/app_log/score-service.log}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%traceId] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
    otlp:
      metrics:
        export:
          url: http://localhost:4318/v1/metrics
          step: 10s
      tracing:
        endpoint: http://localhost:4318/v1/traces
    metrics:
      distribution:
        percentiles:
          do.sleep.method.timed: 0.99, 0.95, 0.9, 0.7, 0.5
          http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
        percentiles-histogram:
          do.sleep.method.timed: true
          http.server.requests: true
        minimum-expected-value:
          do.sleep.method.timed: 100ms
          http.server.requests: 100ms
        maximum-expected-value:
          do.sleep.method.timed: 10s
          http.server.requests: 10s
        slo:
          do.sleep.method.timed: 300ms,500ms,1s,2s
          http.server.requests: 300ms,500ms,1s,2s
    export:
      prometheus:
        enabled: true

  tracing:
    suplier: otel
    sampling:
      probability: 1.0
